
# Project information
site_name: PYCO Documentation
#site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Collod Liam
site_description: >-
  Home of the documentation for PYCO applications. PYCO apps target a VFX-CGI public and help them create
  and work faster. This go from the in-app python script to the standalone app.

# Copyright
copyright: Copyright &copy; 2020 - 2020 Collod-Liam


theme:
  name: material
  features: -tabs
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  language: en
  palette:
    scheme: slate
#    primary: indigo
#    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/PYCO_logo_white.svg
  favicon: img/favicon.png

nav:
    - Home: index.md
    - Standalone:
      - Colorspace Converter:
          - Home: standalone/ColorspaceConvert/home.md
          - Getting started: standalone/ColorspaceConvert/startguide.md
          - Features : standalone/ColorspaceConvert/features.md
    - Maya:
        - Udim Select: maya/udimselect.md
    - About: about.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MrLixm
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/liam-collod/
    - icon: fontawesome/brands/artstation
      link: https://www.artstation.com/monsieur_lixm

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search