
# Project information
site_name: PYCO Documentation
site_url: https://mrlixm.github.io/PYCO/
site_author: Collod Liam
site_description: >-
  Home of the documentation for PYCO applications. PYCO apps target a VFX-CGI public and help them create
  and work faster. This go from the in-dcc python script to the standalone application.

# Copyright
copyright: Copyright &copy; 2020 - 2021 Collod-Liam


theme:
  name: material
  features:
    -tabs
    - search.suggest
    - search.highlight
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  language: en
  palette:
    scheme: slate
#    primary: indigo
#    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/PYCO_logo_white.svg
  favicon: img/favicon.png

nav:
    - Home: index.md
    - Standalone:
      - Colorspace Converter:
          - Home: standalone/ColorspaceConvert/home.md
          - Getting started: standalone/ColorspaceConvert/startguide.md
          - Features : standalone/ColorspaceConvert/features.md
          - Development : standalone/ColorspaceConvert/development.md
          - For Linux: standalone/ColorspaceConvert/linux.md
      - Pointer's Gamut CLI:
          - Home: standalone/PointerGamutCLI/home.md
          - Getting started: standalone/PointerGamutCLI/startguide.md
          - Features : standalone/PointerGamutCLI/features.md
      - EXR Tools:
          - Home: standalone/EXRTools/home.md
          - Getting started: standalone/EXRTools/startguide.md
          - Features: standalone/EXRTools/features.md
          - Development : standalone/EXRTools/development.md

    - Maya:
        - Udim Select: maya/udimselect.md
    - Katana:
        - Texture Monitor:
          - Home: katana/TextureMonitor/home.md
          - Start Guide: katana/TextureMonitor/startguide.md
          - Features: katana/TextureMonitor/features.md
          - Development: katana/TextureMonitor/development.md
        - Megascans Importer:
          - Home: katana/msimporter/home.md
          - Features: katana/msimporter/features.md
    - Licenses:
        - Eula: licenses/eula.md

    - What's new ?: whatsnew.md
    - About: about.md

extra:
  disqus: pyco-apps
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MrLixm
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/liam-collod/
    - icon: fontawesome/brands/artstation
      link: https://www.artstation.com/monsieur_lixm

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
  - attr_list

google_analytics:
  - UA-178298369-1
  - auto

plugins:
  - search
